knp_snappy:
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary:     '%kernel.project_dir%/wkhtmltopdf/bin/wkhtmltopdf.exe'
        options:    []
    image:
        enabled:    true
        binary:     '%kernel.project_dir%/wkhtmltopdf/bin/wkhtmltoimage.exe'
        options: 
         - { name: ‘viewport-size’, value: ‘1024x768’ }
         - { name: ‘page-size’, value: ‘A4’ }